-- MySQL Script generated by MySQL Workbench
-- Sun May  9 10:49:33 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `idUsers` INT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `city` VARCHAR(45) NULL,
  `bio` LONGTEXT NULL,
  `userAttachment` VARCHAR(255) NULL,
  `cover` VARCHAR(255) NULL,
  PRIMARY KEY (`idUsers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dogs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dogs` (
  `idDogs` INT NOT NULL,
  `idUser` INT NOT NULL,
  `icad` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `breed` VARCHAR(45) NOT NULL,
  `birthday` DATE NULL,
  `sexe` TINYINT NULL,
  `size` TINYINT(1) NULL,
  `sterile` TINYINT NULL,
  `dogAttachment` VARCHAR(255) NULL,
  PRIMARY KEY (`idDogs`),
  INDEX `fk_Dogs_Users_idx` (`idUser` ASC),
  CONSTRAINT `fk_Dogs_Users`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Marks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Marks` (
  `idUser` INT NOT NULL,
  `idDogs` INT NOT NULL,
  `isMarked` INT NULL,
  PRIMARY KEY (`idUser`, `idDogs`),
  INDEX `fk_Users_has_Dogs_Dogs1_idx` (`idDogs` ASC),
  INDEX `fk_Users_has_Dogs_Users1_idx` (`idUser` ASC),
  CONSTRAINT `fk_Users_has_Dogs_Users1`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Dogs_Dogs1`
    FOREIGN KEY (`idDogs`)
    REFERENCES `mydb`.`Dogs` (`idDogs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
